### ISSUE TITLE
rsync seems to only keep the last synchronised folder

### ISSUE THREAD

**Issue by linuxbandit** [geerlingguy/ansible-role-backup#13]
Hi,

I set the role with two folders to be synchronised through `backup_directories`. Checking the script outcome, I see that only the second folder's content is present in the target machine.
By fiddling the script, just deleting the `--delete` flag, the expected outcome (i.e. the content of both folders) is achieved.

Is this a bug?

Latest version of the role, `rsync  version 3.1.1  protocol version 31` on the sending machine.

Thank you,
Fabrizio

**Comment by geerlingguy** [comment]
Hmm... `backup_directories` _should_ backup all the directories in that list. I'll have to check if maybe there's an issue with it.

**Comment by linuxbandit** [comment]
Thank you!

I just came back from a 2-weeks course. If you need me to perform any test, I am available

**Comment by linuxbandit** [comment]
Hi,

I am re-working on this, will let you know if the problem occurs again
