### ISSUE TITLE
Problem with Variables and backup_mysql_password in shell script

### ISSUE THREAD

**Issue by manuelgerber** [geerlingguy/ansible-role-backup#17]
Hi Jeff,

i found an issue in the mysql backup shell script. 
The variable $MYSQL_CREDENTIALS contains the mysql user and password. The password is written into the variable with quotation marks. I think this is a problem when the Variable call in a Commandline.

DATABASES=`$MYSQL $MYSQL_CREDENTIALS -e "SHOW DATABASES;" | grep -Ev '(Database|information_schema|performance_schema|mysql)'

The password can then not be interpreted.

That Comman line works for me.

$MYSQLDUMP {% if backup_mysql_credential_file != '' %} --defaults-extra-file={{ backup_mysql_credential_file }} {% else %}  -u {{ backup_mysql_user }} -p'{{ backup_mysql_password }}' {% endif %} --single-transaction --quick --lock-tables=false {{backup_database_name}} | gzip -f -6 > {{ backup_path }}/databases/{{backup_database_name}}_$TIMESTAMP.sql.gz

By the way. I have expand the shell script with a little file versioning. Files that older 10 days will be delete:-)

find {{ backup_path }}/databases -mtime +10 -type f -delete
$RSYNC -aqz -e 'ssh {{ backup_remote_connection_ssh_options }}' {{ backup_path }}/databases $REMOTE:{{ backup_remote_base_path }}/{{ backup_identifier }} --delete

Beste Regards
Manuel

P.S. The Role is very usefull. Thank you!

**Comment by thiagogomesverissimo** [comment]
Same behavior here: 

 - `$MYSQL $MYSQL_CREDENTIALS` - not working
 - `/usr/bin/mysql -u example -p'pass'` -working
