### ISSUE TITLE
error message in tasks/main.yml

### ISSUE THREAD

**Issue by robertbovens** [geerlingguy/ansible-role-backup#18]
```
    backup_remote_host_name: '192.168.1.2'
    backup_remote_host_key: ['-----BEGIN RSA PRIVATE KEY-----
somekey
-----END RSA PRIVATE KEY-----']
```

When trying to run, it spits out the following error message, even without backup_remote_host_key it spits out this error:

fatal: [localhost]: FAILED! => {"msg": "The conditional check 'backup_remote_host_name' failed. The error was: error while evaluating conditional (backup_remote_host_name): float object has no element 1\n\nThe error appears to be in '/home/robert/.ansible/roles/geerlingguy.backup/tasks/main.yml': line 35, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add backup remote host key to server.\n  ^ here\n"}

**Comment by geerlingguy** [comment]
@robertbovens - The host key is supposed to be like:

```yaml
backup_remote_host_key: 'public-host-key-goes-here-pasted-as-string-in-quotes'
```

You can get that host key (don't put the private key from the server there), with `cat /etc/ssh/ssh_host_ecdsa_key.pub` on that server, or you can look up the host key after connecting from another computer in your known_hosts file.

**Comment by robertbovens** [comment]
I tried, it still fails with the same error. 
Even if i remove the backup_remote_host_key sentense it will still give the same error.

I am using ubuntu 20.04.3
ansible 2.9.6
python 3.8.10
