### ISSUE TITLE
2 small issues with the backup.sh.2 template

### ISSUE THREAD

**Issue by tijmenvandenbrink** [geerlingguy/ansible-role-backup#8]
First of all thanks for this role. I found that there are 2 issues with it though. 

1. There's a whitespace after the = which causes the script to fail
2. The script doesn't create the database directory in the backup_path

I'll do a pull request fixing these. Perhaps you can merge it.

Thanks

**Comment by Archetylator** [comment]
Right, I can confirm the first issue. [Here](https://github.com/geerlingguy/ansible-role-backup/blob/master/templates/backup.sh.j2#L25) is the problematic line.
